### ISSUE TITLE
Handling Events

### ISSUE THREAD

**Issue by sorousht** [reactjs/fa.reactjs.org#100]
Translate [Handling Events](https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/handling-events.md) into Persian.

**Comment by angellandros** [comment]
I'm currently working on it.

**Comment by sorousht** [comment]
Hi @angellandros 
Sorry for the late update. Since @black-sheep777 did not submit a PR for this one, please continue your work on this page.
