### ISSUE TITLE
ReactDOM

### ISSUE THREAD

**Issue by sorousht** [reactjs/fa.reactjs.org#105]
Translate [ReactDOM](https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/reference-react-dom.md) into Persian.

**Comment by BaseMax** [comment]
Hello,

We are working on it.
https://github.com/MaxFork/fa.reactjs.org/blob/master/content/docs/reference-react-dom.md

Best,
Max

**Comment by sorousht** [comment]
Assigned to @Abolfazl2647
