### ISSUE TITLE
Can't push

### ISSUE THREAD

**Issue by Abolfazl2647** [reactjs/fa.reactjs.org#123]
hi, i was assigned to translate the page of Lifting State Up.
and i did it.

but first i follow the installation guid as below:
# 1. یک کپی از مخزن کد بگیرید
git clone https://github.com/reactjs/fa.reactjs.org.git

# 2. به شاخه اصلی پروژه بروید
cd fa.reactjs.org

# 3. وابستگی‌های npm پروژه را نصب کنید
yarn

finally i run the project and create my own branch and i have 3 commits since i start the translation but when i try to push i face this error on terminal ..
`
remote: Permission to reactjs/fa.reactjs.org.git denied to Abolfazl2647.
fatal: unable to access 'https://github.com/reactjs/fa.reactjs.org.git/': The requested URL returned error: 403
`

and i also try this:
`git push [my-fork-name] [the-name-of-my-branch]`

but face this one:
`
fatal: 'Abolfazl2647' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`
how can i push ?

(this is my first time to collaborate on code with other people on GitHub)

**Comment by Anisha95** [comment]
how did you solve this ?
