### ISSUE TITLE
Translate Rules of Hooks

### ISSUE THREAD

**Issue by sorousht** [reactjs/fa.reactjs.org#132]
Translate [hooks-rules.md](https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/hooks-rules.md)

**Comment by sorousht** [comment]
Assigned to @Abolfazl2647

**Comment by Abolfazl2647** [comment]
in testi bud dg ?!
:-)

**Comment by sorousht** [comment]
Yes, so I close #132
