### ISSUE TITLE
درخواست همکاری

### ISSUE THREAD

**Issue by amir28** [reactjs/fa.reactjs.org#148]
سلام، به تمام مشارکت کنندگان این پروژه، خیلی دوست دارم توی این پروژه شرکت داشته باشم ولی به دلیل کمی مشکل مالی نمی‌تونم کاملا رایگان انجامش بدم. میخواستم بدونم اجازه می‌دهین به ازای حداقل فلان قدر کاراکتر یک تبلیغات کوچیک در همان مطلب قرار بگیره.
من می‌تونم خیلی توی پروژه مشارکت داشته باشم.
ممنون

**Comment by sorousht** [comment]
سلام @amir28 عزیز!

ما قبلا تلاش کردیم که برای قدردانی از تلاش مشارکت کنندگان این پروژه، هدیه‌ای کوچک درنظر بگیریم. اما متاسفانه میسر نشد. تنها چیزی که مشوق ما در ترجمه اسناد ری‌اکت هست،

**Comment by sorousht** [comment]
سلام @amir28 عزیز،

متاسفانه در حال حاضر ما اجازه این کار رو نداریم و وظیفه ما ترجمه اسناد هست. به این معنی که نباید چیزی به آن اضافه یا از آن کم شود.

از طرف دیگر، بسیار دوست داشتیم که برای مشارکت کنندگان هدیه‌ای در نظر گرفته بشود که میسر نشد.

در حال حاضر تنها مشوق ما در ترجمه این اسناد به زبان فارسی، معرفی ری‌اکت به فارسی زبان ها و شاید کمکی کوچک به دوستانی که در شروع کار یادگیری با زبان فارسی برای آن ها آسان تر باشد.

امیدوارم در آینده راهی برای قدردانی از وقتی که مشارکت کنندگان برای این پروژه صرف می کنند، ایجاد شود

ارادتمند،
سروش
