### ISSUE TITLE
Translate blog/2020/10/20/react-v17.html

### ISSUE THREAD

**Issue by sorousht** [reactjs/fa.reactjs.org#181]

**Comment by sorousht** [comment]
Assigned to @pooooriya

**Comment by pooooriya** [comment]
مواردی که تو سایت اصلی ادیت شده و حذف شده نیاز به ترجمه داره؟
به طور مثال این جمله نیست
We're actively working on the new React features, but they're not a part of this release. The React 17 release is a key part of our strategy to roll them out without leaving anyone behind.

**Comment by sorousht** [comment]
<p dir="rtl">
پروژه اخیرا به‌روز رسانی شد. پس نباید ناهماهنگی وجود داشته باشد. ولی جمله‌ای که شما نوشتید از فایل زیر هست:
</p>
<p>content/blog/2020-08-10-react-v17-rc.md</p>
<p dir="rtl">من فکر می‌کردم که منظور شما این یکی هست:!</p>
<p>content/blog/2020-10-20-react-v17.md</p>
<p dir="rtl">
انتخاب شما کدوم هست؟</p>

**Comment by pooooriya** [comment]
مورد دوم تو فایلا نیست فقط 
فقط RC 
داره

**Comment by sorousht** [comment]
باید دوباره pull کنید که تغییرات جدید رو بگیرید.

**Comment by pooooriya** [comment]
بعد از ترجمه این پست پست قبلی مربوط به ریلیز کاندیدت هم به بنده تخصیص بدهید منتهی به علت مشغله کاری انشاله  تا هفته آبنده ارسال میکنم

**Comment by sorousht** [comment]
> بعد از ترجمه این پست پست قبلی مربوط به ریلیز کاندیدت هم به بنده تخصیص بدهید منتهی به علت مشغله کاری انشاله تا هفته آبنده ارسال میکنم

مشکلی نیست، وقتی این صفحه تمام بشود، می توانید روی صفحه بعدی کار کنید. ولی اگر شما مشتاق هستید، صفحاتی1

**Comment by sorousht** [comment]
مشکلی نیست، ولی اگر مشتاق هستید پیشنهاد من ترجمه صفحاتی هست که ماندگاری بیشتری نسبت به پست بلاگ دارند و در دستور کار ما هستند. از اینجا #1 می تونید لیست صفحات رو ببینید.

**Comment by pooooriya** [comment]
i cant push to my branch i,v got 403 error i also checked my remote and login info

**Comment by pooooriya** [comment]
با توجه به نبودن یک ریسورس خوب برای ری اکت 17 خواهشمندم این مورد که ریکوست ارسال کردم را زودتر بررسی بفرمایید تا توسعه دهندگان ایرانی راحت تر بتوانند از ویژگی های جدید ری اکت بهره ببرند
