### ISSUE TITLE
کمک برای ترجمه

### ISSUE THREAD

**Issue by AlMoosavi** [reactjs/fa.reactjs.org#228]
به نام خدا
سلام
بنده هم می خواهم در ترجمه کمک کنم
فقط یک صفحه را به من معرفی کنید تاترجمه کنم
من میدونم که فایل های 
.md
باید ترجمه بشوند
از داخل سایت گیت همین کار را انجام دادم ولی ظاهرا نتیجه ای در بر نداشته
باتشکر

**Comment by AlMoosavi** [comment]
ممنون از شما
بررسی کردم 
همه چیز ردیفه
ولی اساتید محترم اگر نکته ای هست
ممنون میشم راهنمایی بفرمائید

**Comment by sJJdGG** [comment]
<div align="right" dir="right">
سلام
میتونی برای نمونه به پول‌ریکوئست‌هایی که بچه‌ها باز کردند نگاه کنی تا نحوه کلی انجام کار دستت بیاد
اگه نکته‌ای هم باشه توی بررسی پول ریکوئست گفته میشه
با تشکر
</div>
