### ISSUE TITLE
ترجمه توسط جامعه ری‌اکت ایران

### ISSUE THREAD

**Issue by amerllica** [reactjs/fa.reactjs.org#29]
<div dir="rtl">
با سلام.
من یکی از اعضای و اونرهای <a href="https://iran-react-community.github.io">جامعه ری‌اکت ایران</a> هستم. 
لینک اورگان ما هم توی گیت‌هاب <a href="https://github.com/iran-react-community">اینجاست</a>.
<br/>
از این ریپو شما یک فورک گرفتم و استارت شروع رو زدیم. اعضای ما زیاد هستند، می‌خوایم همکاری کنیم و کار رو جلو ببریم. من تمام راهنماهای شما رو خوندم.
<br/>
فقط نمی‌دونم شما دقیقا روی کدوم قسمت‌ها کار نمی‌کنید که ما روی اون‌ها کار کنیم.

لطفا راهنمایی کنید.
</div>

**Comment by sorousht** [comment]
<p dir="rtl">
سلام @amerllica عزیز
</p>
<p>
خیلی خوشحالم که علاقه‌مند هستید و به جمع ما خوش آمدید.
</p>
<p>
هدف اولیه ما ترجمه Core Pages هست. اینجا #1 لیست صفحات هست و هر مشارکت‌کننده یک صفحه رو (ترجیا به ترتیبی که نوشته‌شده) انتخاب و اعلام می‌کنه و یکی از نگاه‌دارندگان پروژه اسم اون شخص رو روبروی عنوان صفحه اضافه می‌کنه که دیگران هم درجریان باشند و تداخل پیش نیاد. در آخر هم بعد از ادغام کد با مخزن اصلی، صفحه مورد نظر تیک می‌خوره و تمام!
</p>
<p>
برای مثال صفحات زیر برای شروع پیشنهاد می‌شه:
</p>
<ul>
<li><a href="https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/handling-events.md">Handling Events</a></li>
<li><a href="https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/conditional-rendering.md">Conditional Rendering</a></li>
<li><a href="https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/lists-and-keys.md">Lists and Keys</a></li>
</ul>
<p>
این توضیحات رو به صفحه <a href="https://github.com/reactjs/fa.reactjs.org/blob/master/CONTRIBUTING.md">نحوه مشارکت</a> اضافه می کنم که دوستان جدیدمون راحت‌تر با شیوه  کار آشنا شوند.
</p>
<p>
اگر بازهم سوالی بود من درخدمتم :)
</p>

**Comment by amerllica** [comment]
<div dir=rtl>
ممنونم سروش عزیزم

این سه صفحه رو برمی‌دارم و از بچه‌های جامعه فقط خودم و نیما کار می‌کنیم روش. یکم دستمون که راه افتاد و ابزارهای بهتری پیدا کردیم برای بقیه هم بازش می‌کنیم. ما حدود ۱۰۰ نفریم.

فقط من یه مشکل توی اجرا  و یه سوال دیگه هم دارم.

من یه فورک گرفتم و مستر رو yarn کردم این شد:
![image](https://user-images.githubusercontent.com/10472437/53648582-7be4f500-3c55-11e9-944e-fd86902ae0e8.png)


و اینکه اون برنچ‌های fa و اون سه تا sync چی هستن؟

ما سیستم رو اینطوری می‌چینیم که develop رو دیفالت می‌کنیم و مستر ما فقط از برنچ استیبل شما آپدیت میگیره، اعضای جامعه ری‌اکت هم روی دولوپ ما PR می‌دن.

اگر ممکنه یه کوچولو برنچ‌های ما رو توضیح بدین.
</div>

**Comment by sorousht** [comment]
<p dir="rtl">
@amerllica عزیز
</p>
<p dir="rtl">
از متن خطا متوجه شدم که نسخه node  سیستم شما ۱۰.۱۴.۲ هست. همون طور که توی README اشاره شده، باید از node نسخه ۸ استفاده بشه. اگر مشکل با تغییر نسخه node حل نشد، حتما به من خبر بدید.
</p>
<p dir="rtl">
و در مورد روش کار و شاخه‌ها توضیح کوتاهی در صفحه راهنمای مشارکت کنندگان آورده شده. اون شاخه هایی که با <code>sync-</code> شروع می شوند، برای به روز رسانی مخزن کد فارسی با اصلی هست و ما کاری با اون‌ها نداریم. اما روش کار به این صورت هست که شما PR رو به شاخه <code>fa</code> ارسال می کنید و پس از بررسی، ادغام می‌شود. پس از مدتی، وقتی موارد جدید برای انتشار آماده شد، تعییرات شاخه <code>fa</code> توسط نگاه‌دارندگان با <code>master</code> ادغام و منتشر می‌شود.
</p>

<p dir="rtl">اگر سوالی بود، حتما بپرسید :)</p>

**Comment by amerllica** [comment]
<div dir=rtl>
مرسی سروش عزیز

از کمکتون ممنونم. ما برای دولوپ برنامه‌هامون باید از آخرین نسخه node استفاده کنیم. فکر کنم باید از nvm استفاده کنم تا درست بشه. راستش توی فایل توضیحات README خونده بودم ولی فکر نمی‌کردم که نسخه بالاتر رو پشتیبانی نکنه.


در مورد PR ها هم کاملا متوجه شدم. من ریپوی فورک شده رو درستش می‌کنم. اون sync ها رو پاک می‌کنم. ما با سیستم‌های خودمون پیشروی می‌کنیم که توضیحاتم در مورد سیستم کاری ما، برای شما جزمزاحمت چیز دیگه‌ای نیست. مهم اینه در نهایت ما به برنچ fa یک PR ارسال می‌کنیم و الباقی باشماست. 

امید به خدا که این مهم پیشروی خوبی داشته باشه.

عرضی نیست. اگر مورد دیگه‌ای بود در یک issue جدا مطرح می‌کنم. با تشکر
</dir>

**Comment by sJJdGG** [comment]
@amerllica 
تشکر بابت وقتی که میگذارید
در مورد اون ارورت هم که خود من از داکر استفاده میکنم
راه دیگه هم بدون استفاده از nvm نصب ورژن ۸ بدون اضافه کردنش به path هستش

**Comment by amerllica** [comment]
@sJJdGG 
<div dir=rtl>
ممنونم از اینکه پیام من رو دیدید، فقط من نیستم که می‌خوام روی این پروژه ارزشمند کار کنم، جامعه ری‌اکت کارهای ایران پشتش هستند. من فقط دارم هماهنگی‌ها رو انجام میدم که الباقی دوستان هم بتونن بیان و کمک کنن.

من برای مشکلم از nvm استفاده کردم ولی باز هم توی اجرا مشکل دارم. فکر کنم ایندفعه yarn م با نسخه نود هشت هماهنگ نیست.
</div>

**Comment by sorousht** [comment]
<p>@amerllica عزیز،</p>
<p dir="rtl">
اگر مشکل برطرف نشد، متن خطا رو اینجا قرار بده، شاید با کمک هم بتونیم برطرفش کنیم.
</p>
<p>در مورد ترجمه یک پیشنهاد دارم. از ترجمه صفحه اول (یعنی <a href="https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/handling-events.md">Handling Events</a>) شروع کنید. اینطوری با روال کامل کار آشنا می‌شوید و کار برای صفحه‌های بعدی آسان‌تر خواهد شد. اگر موافق هستید، من صفحه اول رو به خود شما واگذار کنم؟ </p>

**Comment by amerllica** [comment]
Dear @sorousht 

<div dir=rtl>
صددرصد موافقم، همونطور که در پست‌های بالاتر خود شما فرمودید سه صفحه:
<ul>
<li>Handling Events</li>
<li>Conditional Rendering</li>
<li>Lists and Keys</li>
</ul>
رو من «ما» کار می‌کنیم.

مساله اینه که من نمیتونم پروژه رو run بگیرم و واقعا هرکاری دستم بر اومده کردم. از nvm هم استفاده کردم ولی باز همون خطایی رو گرفتم که در بالا عکسش رو گذاشتم. اگر اینطوری نمیشه یه داکر ایمیج بهم بدید که بتونم راش بندازم
</div>

**Comment by amerllica** [comment]
Dear @sorousht , @sJJdGG 

<div dir=rtl>
مشکل من حل شد، بارها این اتفاق افتاده برام و باز هم یادم میره اول این رو چک کنم، مشکل من فایل yarn.lock بود.

پاکش کردم و خودم yarn install گرفتم و درست شد.

خطاها به خاطر نسخه node نبود، هرچند ممنونم، باعث شد بشینم داک nvm رو بخونم و کامل برای سیستم خودم تنظیمش کنم.

فقط تنها سوالم اینه که الآن فایل yarn.lock خودم رو پوش کنم؟ و توی اون PR ـی که از طرف خودمون برای شما ارسال می‌کنم هم این رو بگذارم؟
</div>

**Comment by sorousht** [comment]
<p dir="rtl" >
سلام مجدد @amerllica
</p>
<p dir="rtl">
خوبه که حل شد! فایل <code>yarn.lock</code> هم به نظر من باید کامیت بشه.
</p>
<p dir="rtl">
در مورد صفحه‌ها، ترجیح تیم ترجمه اینه در یک زمان بیش از یک صفحه به یک شخص واگذار نشود. چون شما نماینده تیم هستید، من صفحه اول رو به شما واگذار می‌کنم. بعد از انجامش صفحه دیگری رو انتخاب کنید و با همین روش پیش می‌ریم. 
هر سوال یا کمکی نیاز بود من در خدمتم.
</p>

**Comment by amerllica** [comment]
Dear @sorousht 

<div dir=rtl>
فایل yarn.lock رو توی گیت ایگنور گلوبالم گذاشتم. فکر نکنم درست باشه شما yarn.lock من رو داشته باشید. وقتی شما هیچ مشکلی باهاش ندارید. ولی باز هم اگر نیازه بفرمایید که از توی ایگنور درش بیارم و پوش کنم.

در مورد واگذاری هم به نظرم شروع شما با تخصیص یک صفحه به من کار خوبیه. ولی به نظرم در آینده یه قسمت رو بدید به من که من روی ترلو به بچه‌هامون بدم و کار ترجمه رو انجام بدند.
</div>

**Comment by sJJdGG** [comment]
اگه میخوای استثنا مربوط به فایل yarn.lock رو به .git/info/exclude میتونی اضافه کنی.
این فایل مثل .gitignore ئه ولی مثل اون فایل پوش نمیشه و لوکاله و توی pr هم نمیاد.

بتز اگه مشکلی بود بگو هر کمکی از دستمون بربیاد میکنیم
@amerllica

**Comment by amerllica** [comment]
Dear @sJJdGG 

<div dir=rtl>
مرسی سجاد جان، من فایل <code>yarn.lock</code> رو در گیت ایگنور گلوبالم قرار دادم. آدرسش <code>~/.gitignore_global</code> هست. درست شد. از سروش هم یک صفحه گرفتم ترجمه می‌کنم و از طریق کامیونیتی ری‌اکت براتون PR ارسال می‌کنم.

موضوع اینه برای آینده خواهشا به من درخت بدید، بین بچه‌هامون تقسیم می‌کنیم سعی می‌کنیم در کنار کیفیت، کمیت بیشتری رو هم پشتیبانی کنیم. 

تنها خواهش من همینه. ممنونم.
</div>
