### ISSUE TITLE
نحوه استفاده از react.js  فارسی

### ISSUE THREAD

**Issue by MortezaHeydari97** [reactjs/fa.reactjs.org#35]
چطور میتونم از نسخه فارسی آموزش react.js استفاده کنم؟؟؟؟؟؟؟؟
لینکش کجاست؟؟؟؟ میشه لینکشو برام بفرستید؟؟؟

**Comment by sJJdGG** [comment]
<p dir='rtl'>
با سلام. هنوز ترجمه به حداقل ممکن نرسیده که سایت رسمی آنلاین بشه. ولی شما میتونید با مراجعه به pull request ها آخرین پیش نمایش رو روی netlify بیبندید بدون این که نیاز به fork رپو داشته باشید.
</p>

<p dir='rtl'>
برای مثال آخرین پیش نمایش سایت ترجمه شده در زمان نگارش آدرس زیر میباشد:
</p>

https://deploy-preview-34--fa-reactjs.netlify.com/

**Comment by MortezaHeydari97** [comment]
خیلی ممنونم از شما دوست عزیز و بزرگوار.
چطور میتونم از اخرین تغییرات و یا عوض شدن لینکی که بهم دادین با خبر بشم ؟

پیشنهاد میکنم اگر امکانش هست، لینک رو یه جایی قرار بدین که قابل دسترس تر
باشه، از نظر UX میگم.
