### ISSUE TITLE
Remove `fa` branch

### ISSUE THREAD

**Issue by sorousht** [reactjs/fa.reactjs.org#52]
<p dir="rtl">
اوایل شروع کارمون، تصمیم گرفتیم که یک شاخه (fa) درست کنیم و دلیلش این بود:
<br />
<br />
۱. این الگو رو از تیم‌های دیگه برداشتیم
<br />
۲. فکر می‌کردیم که روند بررسی رو بهبود می‌دهد
<br />
۳. هنگامی که تغییرات بررسی و آماده انتشار شد با master ادغام کنیم.
<br />
<br />
اما تا اینجای کار مزیتی برای ما نداشته! شاید در آینده پس از اینکه انتشار داشتیم، شاخه pre-release یا یه چیزی شبیه اون اضافه کنیم ولی در حال حاضر بنظر می‌رسد که نیازی نیست. نظر شما چیه؟
</p>

**Comment by seven-deuce** [comment]
برای منی که آشنایی زیادی با گیت هاب ندارم مسلما راحت تر می کنه که یک شاخه ی مستر باشه.

**Comment by theiliad** [comment]
The `fa` branch definitely causes multiple issues.

If one person opens up a PR to the branch, any future PRs opened (while the existing PR is still open) will include the commits from the open PR

**Comment by x1smind** [comment]
In TRANSLATION.md, please correct the following:

Ansestor is misspelled. (Correct: Ancestor) 
Ansestor is repeated for the plural form. (Correct: Ancestors)
Epaque is misspelled. (Correct: Opaque)

**Comment by sJJdGG** [comment]
LGTM

**Comment by sorousht** [comment]
تصمیم بر این شد که شاخه `fa` حذف و از ‍‍`master` استفاده شود.

**Comment by sJJdGG** [comment]
Branch has been deleted!
