### ISSUE TITLE
Introducing JSX

### ISSUE THREAD

**Issue by sorousht** [reactjs/fa.reactjs.org#99]
Translate [Introducing JSX ](https://github.com/reactjs/fa.reactjs.org/blob/master/content/docs/introducing-jsx.md)into Persian

**Comment by sorousht** [comment]
Assigned to @groprog

**Comment by groprog** [comment]
@sorousht I forget translate this line "With that out of the way, let’s get started!" .
Now what I do ? make a PR again or ...

**Comment by Abolfazl2647** [comment]
@sorousht What can we do about this ?
